version: "2"
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672 # port for the daemon API
      - 15672:15672 # port for the RabbitMQ management interface
  worker:
    build: worker
    restart: always
    links:
      - rabbitmq
    environment:
      - AWS_SECRET_ACCESS_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_DEFAULT_REGION
      - S3_BUCKET_NAME
    command: ./run_in_s3.sh python worker.py -p 5672 -s rabbitmq -o "M56_tiles_detections"
  submit:
    build: submit
    restart: never
    links:
      - rabbitmq
    environment:
      - AWS_SECRET_ACCESS_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_DEFAULT_REGION
      - S3_BUCKET_NAME
    command: ./run_in_s3.sh python submit.py -p 5672 -s rabbitmq -i "M56_tiles"
